### ISSUE TITLE
PyPi installation does not work

### ISSUE THREAD

**Issue by renxida** [pierrebaudot/infotopopy#5]
Hi Pierre!

I loved your work. Reading your slides was a treat. And I'm super excited about using your tool.

One thing though is, running 
`pip install infotopo`
and then doing
`import infotopo`

gives me a "no such module" error.

I'm guessing it has something to do with `pip install` giving me only `~/xr5ry/anaconda3/lib/python3.9/site-packages/infotopo-0.2.10.dist-info` and not the actual code.

If you're actively maintaining this repo, please just let me know how I can help and I'll provide more information or, if you'd like, attempt to fix it and submit a pull request!

**Comment by pierrebaudot** [comment]
Dear Xida,
Yes, sorry for the problem I never found the time to fix. The setup file has now a  bug. I am not sure I will have time to fix it since I would prefer dedicating time in GPU and pytorch inclusion of the algos. If you want to have a try urgently I recommend that you use the infotopo.py directly : it works well and self sufficient to run all the functions in the tuto (this is how i do now).  The examples of the tutorials are in the "__main__"  .
Kind regards and my appologies for the inconvenience
Pierre

**Comment by renxida** [comment]
Dear Pierre,

That's perfectly understandable! 

I went ahead and made some changes that should fix the problem! Feel free to integrate it into this repo by approving the pull request!

Best,
Xida

**Comment by fingoldo** [comment]
Guys, should not the pip package be updated as well? otherwise, the fix is not working )
